version: '3'
services:
  web-experiments:
    container_name: web-experiments
    pull_policy: build
    build: .
    ports:
      - 3001:3001
    labels:
      - "traefik.http.routers.web-experiments.rule=Host(`experiments.cheekysim.com`)"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_default
